plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

repositories {
	maven {
		url = "https://masa.dy.fi/maven/sakura-ryoko"
		content { includeGroupAndSubgroups("fi.dy.masa") }
	}
	maven {
		url = 'https://maven.fallenbreath.me/releases'
		content { includeGroupAndSubgroups("me.fallenbreath") }
	}
	maven {
		url = 'https://maven.terraformersmc.com/releases/'
		content { includeGroupAndSubgroups("com.terraformersmc") }
	}
	maven { url = 'https://jitpack.io' }
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"schematic-synchronizer" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	clientImplementation "fi.dy.masa.malilib:malilib-fabric-26.2:0.29.4"
	clientImplementation "fi.dy.masa.litematica:litematica-fabric-26.2:0.28.5"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 25
}

java {
	withSourcesJar()
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}
